### ISSUE TITLE
[DS105] Why do some Windows users get assigned to `root` instead of their usernames when installing WSL?

### ISSUE THREAD

**Issue by jonjoncardoso** [LSE-DSI/DS105#2]

**Comment by Mayazure** [comment]
https://github.com/microsoft/WSL/issues/4276#issue-464846598

**Comment by jonjoncardoso** [comment]
We shared the links with students, and most who had that problem seemed to have gotten it fixed. 

I added a `feature request` tag to this issue so we can incorporate direct instructions about it in the future
